// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc691.Steve;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.CANTalon;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.Servo;
import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANTalon driveTrainRRMotor;
    public static CANTalon driveTrainFRMotor;
    public static CANTalon driveTrainRLMotor;
    public static CANTalon driveTrainFLMotor;
    public static SpeedController elevatorLeftElevatorMotor;
    public static SpeedController elevatorRightElevatorMotor;
    public static SpeedController elevatorLeftRopeSweeper;
    public static SpeedController elevatorRightRopeSweeper;
    public static DoubleSolenoid elevatorRopeClawSolenoid;
    public static DigitalInput elevatorTopLimitSwitch;
    public static DigitalInput elevatorBottomLimitSwitch;
    public static DigitalInput elevatorDavitLimitSwitch;
    public static Solenoid gearShootGearDropper;
    public static Servo cameraXServo;
    public static Servo cameraYServo;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainRRMotor = new CANTalon(1);
        LiveWindow.addActuator("DriveTrain", "RR Motor", driveTrainRRMotor);
        
        driveTrainFRMotor = new CANTalon(2);
        LiveWindow.addActuator("DriveTrain", "FR Motor", driveTrainFRMotor);
        
        driveTrainRLMotor = new CANTalon(3);
        LiveWindow.addActuator("DriveTrain", "RL Motor", driveTrainRLMotor);
        
        driveTrainFLMotor = new CANTalon(4);
        LiveWindow.addActuator("DriveTrain", "FL Motor", driveTrainFLMotor);
        
        elevatorLeftElevatorMotor = new Talon(0);
        LiveWindow.addActuator("Elevator", "Left Elevator Motor", (Talon) elevatorLeftElevatorMotor);
        
        elevatorRightElevatorMotor = new Talon(1);
        LiveWindow.addActuator("Elevator", "Right Elevator Motor", (Talon) elevatorRightElevatorMotor);
        
        elevatorLeftRopeSweeper = new Spark(2);
        LiveWindow.addActuator("Elevator", "Left Rope Sweeper", (Spark) elevatorLeftRopeSweeper);
        
        elevatorRightRopeSweeper = new Spark(3);
        LiveWindow.addActuator("Elevator", "Right Rope Sweeper", (Spark) elevatorRightRopeSweeper);
        
        elevatorRopeClawSolenoid = new DoubleSolenoid(0, 0, 1);
        LiveWindow.addActuator("Elevator", "Rope Claw Solenoid", elevatorRopeClawSolenoid);
        
        elevatorTopLimitSwitch = new DigitalInput(0);
        LiveWindow.addSensor("Elevator", "Top Limit Switch", elevatorTopLimitSwitch);
        
        elevatorBottomLimitSwitch = new DigitalInput(1);
        LiveWindow.addSensor("Elevator", "Bottom Limit Switch", elevatorBottomLimitSwitch);
        
        elevatorDavitLimitSwitch = new DigitalInput(2);
        LiveWindow.addSensor("Elevator", "Davit Limit Switch", elevatorDavitLimitSwitch);
        
        gearShootGearDropper = new Solenoid(0, 2);
        LiveWindow.addActuator("Gear Shoot", "Gear Dropper", gearShootGearDropper);
        
        cameraXServo = new Servo(4);
        LiveWindow.addActuator("Camera", "XServo", cameraXServo);
        
        cameraYServo = new Servo(5);
        LiveWindow.addActuator("Camera", "YServo", cameraYServo);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
